CREATE TYPE email_tone AS ENUM ('PROFESSIONAL', 'FRIENDLY', 'BOLD', 'HUMBLE');
CREATE TYPE email_style AS ENUM ('CONCISE', 'DETAILED', 'STORYTELLING');
CREATE TYPE application_status AS ENUM (
  'SAVED', 'APPLIED', 'PHONE_SCREEN', 'INTERVIEW',
  'OFFER', 'REJECTED', 'WITHDRAWN'
);
